5/feat api salvar progresso exercicio
Aceleradora25/e-acelera-back pull request #1
Opened 2024-11-27 18:51 UTC by Wander06

#5 - feat api salvar progresso exercicio
====
  
### 🆙 CHANGELOG

- Criado: estrutura de controllers, services e middlewares
- Logica de verificação de autenticação de usuário
- Mudança de status do exercicio do usuário

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

 **Primeiro de tudo certifique-se de seguir o  passo a passo de README.md caso seja sua primeira vez usando o back-end do e-acelera para configurações iniciais**

- [ ] Rodar git pull na main
- [ ] Abrir branch 5/feat api salvar progresso exercicio
- [ ] Rodar git pull
- [ ] Rodar comando npx prisma migrate dev para puxar as ultimas alterações das migrations
- [ ] Rodar comando npm run dev para inicializar a aplicação 
- [ ] Colocar no arquivo .env a chave JWT (Pedir para Wander)
- [ ] Criar usuario na tabela User com email: teste@gmail.com, no banco de dados local
- [ ] Criar exercicio na tabela Progress com itemId: rw17169056027059821dc
- [ ] Rodar comando "npx ts-node src/script/jwtGenerator.ts", para gerar token do usuario de teste
- [ ] Abrir postman 
- [ ] Acessar a rota put: http://localhost:5002/exercise/rw17169056027059821dc/status
- [ ] Abrir campo header do postman, no campo de **key** escreva "Authorization" e no campo de **value** escreva: 
Bearer <token gerado para usuario de teste>
- [ ] Abrir body do postman e adicionar um {  "itemStatus": "NotStarted"}, pode ser NotStarted, InProgress ou Completed
- [ ] Enviar requisição, deve retornar um status 200 e um objeto parecido com: 
{
    "id": 2,
    "itemId": "rw17169056027059821dc",
    "itemStatus": "NotStarted",
    "elementType": "Exercise",
    "userId": 2
}
- [ ] Analisar casos de erro ex: colocar status errado, token invalido e etc 
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2024-12-03 00:12 UTC, daniellemadrid requested changes
nomes das tabelas

2024-12-03 00:12 UTC, daniellemadrid commented on prisma/migrations/20241003183617_nome_da_migracao/migration.sql
> +CREATE TABLE "Progress" (
podemos alterar o nome para progress

2024-12-03 00:12 UTC, daniellemadrid commented on prisma/migrations/20241003183617_nome_da_migracao/migration.sql
> +CREATE TABLE "User" (
alterar o nome para users, user é uma palavra muito reservada

2024-12-11 16:18 UTC, daniellemadrid approved these changes

2024-12-15 23:39 UTC, oGuilhermeSoares approved these changes
Código aprovado testado.

2024-12-15 23:39 UTC, merged